import { mkdir, writeFile } from "node:fs/promises";
import { instructionsMarkdown } from "@toolgraft/agent-core";
const guide = instructionsMarkdown();
await mkdir("docs", { recursive: true });
await writeFile(
  "docs/generated-agent-instructions.md",
  "<!-- Generated by pnpm docs:generate; edit packages/agent-core/src/index.ts. -->\n\n" +
    guide,
);
await writeFile("packages/brand/assets/agent-instructions.md", guide);
await writeFile(
  "packages/brand/assets/llms.txt",
  "# ToolGraft\n\nFree, open-source website tools by Particular Labs. No internal AI.\n\n- [Agent instructions](./agent-instructions.md): connect, create, approve, verify and repair.\n- [Setup](./get-started.html): install the extension and one local MCP package.\n- [Guide](./agent-guide.html): workflow and current limitations.\n",
);
await writeFile(
  "skills/toolgraft-authoring/SKILL.md",
  "---\nname: toolgraft-authoring\ndescription: Create, test, or repair website adapters using ToolGraft MCP and the user's existing agent. Use when a user wants structured tools for a website or needs a broken ToolGraft adapter fixed.\n---\n\n<!-- Generated by pnpm docs:generate; edit packages/agent-core/src/index.ts. -->\n\n" +
    guide,
);
